site_name: The Access Point
repo_url: https://github.com/Digital-Business-Council/Access-Point 
pages:
    - 'Audience': 'index.md'
    - 'Disclaimer': 'disclaimer.md'
    - 'Overview': 'overview.md'
    - 'Conformance': 'conformance.md'
theme: mkdocs
